### ISSUE TITLE
No content-length HTTP Header and Range request doesn't work will cause job fire in endless loop

### ISSUE THREAD

**Issue by linbo** [discoproject/disco#367] opened 2014-01-01 16:16 UTC
Disco schema support HTTP address, if HTTP response header sent without 'content-length' header, job will fire in endless loop.

The reason is the __len__ method of  Connection class in disco.comm module, which rely on the value from 'content-length'.

so for method  _read_chunk, if 'content-length' is missing and Range request header doesn't work, then method __iter__ will in request endless loop.

``` python

def _read_chunk(self, n):
        if self.buf is None or self.i >= len(self.buf):  # self.i == len(self.buf)
            if self.eof:    # it is False due to no content-length header
                return b''
            self.i = 0
            if len(self):
                end = min(len(self), self.offset + CHUNK_SIZE) - 1
            else:
                end = self.offset + CHUNK_SIZE - 1
            headers = auth_header(self.token)
            headers.update(range_header((self.offset, end)))
            self.response = request('GET',
                                    self.url,
                                    headers=headers)  # it will request again and again since range header doesn't work
            self.buf = self.response.read()
            self.orig_offset = self.offset
            self.offset += len(self.buf)
            if len(self) and self.offset >= len(self):
                self.eof = True
            elif self.buf == b'':
                self.eof = True
        ret = self.buf[self.i:self.i + n]
        self.i += len(ret)
        return ret
```

**Comment by pooya** [comment] 2014-01-04 14:07
This is a duplicate of issue #252. Would you please provide the output of the following command:
echo -e "GET index HTTP/1.1\n\n" | nc localhost 1337
Then I can create a test and verify dangra's patch.
Thanks.

**Comment by linbo** [comment] 2014-01-04 15:16
@pooya  It just a simple node test server

``` javascript
var http = require('http');
http.createServer(function (req, res) {
  if(req.url == '/index'){
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World');
  }
}).listen(1337);
console.log('Server running at http://127.0.0.1:1337/');
```

The nc result

``` bash
$ echo -e "GET /index HTTP/1.1\n\n" | nc localhost 1337
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Sat, 04 Jan 2014 15:14:04 GMT
Connection: keep-alive
Transfer-Encoding: chunked

b
Hello World
0
```

**Comment by pooya** [comment] 2014-01-05 19:25
Thanks.
Commit 6de939b should resolve this issue.

**Closed as completed** 2014-01-08 15:55 UTC
Labels: bug
