### ISSUE TITLE
job gets stuck with waiting -1

### ISSUE THREAD

**Issue by alexcepoi** [discoproject/disco#558] opened 2014-07-21 10:15 UTC
Sometimes jobs seem to get stuck in disco and are not killed by the timeout. The web interface reports a weird "-1" as number of waiting tasks.

![disco_hang_waiting](https://cloud.githubusercontent.com/assets/215764/3642169/3148036a-10be-11e4-9dae-b213f970559d.png)

All nodes are available and work as usual. The only thing I see relevant in the logs are [these lines](https://gist.githubusercontent.com/alexcepoi/0888538ce3738c37cc72/raw/a17acd8917237b625df259b3ef01b60351e7b34f/disco.log).

Not really sure where to go from here, any ideas?

**Comment by pooya** [comment] 2014-07-21 12:26
Thanks for reporting this @alexcepoi Are you using version 0.5.2? Also, would you please let me know how many nodes you have and how many workers each of them has?

**Comment by alexcepoi** [comment] 2014-07-21 12:42
v0.5.2 yes, with a few small settings changes which should not be relevant (FTR [here](https://github.com/scrapinghub/disco/compare/scrapinghub-0.5))

Running a cluster of 4 nodes, 12 workers each. Let me know if I can provide any more relevant details.
Many thanks.

**Comment by pooya** [comment] 2014-07-21 16:52
@alexcepoi I finally reproduced this issue. You might want to increase the TASK_SUBMIT_TIMEOUT value in master/src/job_coordinator.erl to a bigger value (like  5000 ms) to work around this problem for now. I'll be working on root-cause-analysis and a fix later.

**Comment by pooya** [comment] 2014-07-21 17:23
The problem is that the disco_server:new_task is not idempotent. If we call this function and the call times out, we do not whether the fair_scheduler:new_task is called or not. If it is called and then the task submission times out, job_coordinator will retry the task and there will be inconsistencies.
In order to avoid this problem, we can set the task submission timeout to infinity or cast the message to the disco_server instead of calling it.

**Comment by pooya** [comment] 2014-07-22 21:00
This issue should be resolved by 24ba07d4ee6650a035d99fe779df16485343d615. Please re-open if it persists.

**Closed as completed by pooya** 2014-07-22 21:00 UTC
Labels: scheduler

**Comment by alexcepoi** [comment] 2014-07-28 11:02
Indeed this fixes it, many thanks!
