### ISSUE TITLE
Module import error on master

### ISSUE THREAD

**Issue by lud4ik** [discoproject/disco#500] opened 2014-04-30 10:25 UTC
I specified required_modules as job attr:

```
job.required_modules = [('mymodule.jobs.myjob',
                                        os.path.join(cur, 'jobs', 'myjob.py'))]
```

I've set PYTHON_PATH as mentioned in http://disco.readthedocs.org/en/develop/lib/worker/index.html#modspec

I receive error:

```
File "/usr/local/var/disco/data/disco1/62/MyJob@576:d0467:65d92/usr/lib/python2.7/dist-packages/disco/worker/__init__.py", line 317, in main
    task = cls.get_task()
  File "/usr/local/var/disco/data/disco1/62/MyJob@576:d0467:65d92/usr/lib/python2.7/dist-packages/disco/worker/__init__.py", line 402, in get_task
    return Task(**dict((str(k), v) for k, v in cls.send('TASK').items()))
  File "/usr/local/var/disco/data/disco1/62/MyJob@576:d0467:65d92/usr/lib/python2.7/dist-packages/disco/task.py", line 70, in __init__
    self.jobobjs = dPickle.loads(self.jobpack.jobdata)
ImportError: No module named mymodule.jobs.myjob
```

**Comment by pooya** [comment] 2014-06-17 14:20
@lud4ik Disco tries to import this module and fails. Is it in the python path?

**Comment by pooya** [comment] 2014-06-23 14:22
Closing this issue because it cannot be reproduced. Please re-open this issue if you could reproduce it on HEAD.

**Closed as completed by pooya** 2014-06-23 14:22 UTC
