### ISSUE TITLE
Mark node for migration

### ISSUE THREAD

**Issue by jflatow** [discoproject/disco#220] opened 2010-11-19 23:21 UTC
If a node (or a set of nodes) are about to be decommissioned, it would be useful to be able to mark them such. This would force re-replication of data stored on the node, although reading would be still allowed.

**Comment by pmundkur** [comment] 2012-01-23 22:48
This is now supported by the new GC; UI support pending.

**Comment by pmundkur** [comment] 2012-01-23 22:50
Duplicate of #201.

**Closed as completed by pmundkur** 2012-01-23 22:50 UTC
Labels: ddfs
